#pragma once

#define REGISTER_OUTGOING_MESSAGE_CANCEL(MESSAGE_TYPE) \
		_##MESSAGE_TYPE.CancelOutgoingMessages();

#define REGISTER_MESSAGE_CLEARER(MESSAGE_TYPE) \
		_##MESSAGE_TYPE.ClearSentMessages();

#define REGISTER_MESSAGE(MESSAGE_TYPE) \
private: \
	MessageBuffer<##MESSAGE_TYPE> _##MESSAGE_TYPE; \
public: \
	void InsertMessage(##MESSAGE_TYPE message) \
	{ \
		_##MESSAGE_TYPE.InsertOutgoingMessage(message); \
	}

#define REGISTER_THREAD_SAFE_MESSAGE(MESSAGE_TYPE) \
private: \
	ThreadSafeMessageBuffer<##MESSAGE_TYPE> _##MESSAGE_TYPE; \
public: \
	void insertMessage(##MESSAGE_TYPE message) \
	{ \
		_##MESSAGE_TYPE.InsertOutgoingMessage(message); \
	}

#define REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(MESSAGE_TYPE) \
private: \
	LockFreeThreadSafeMessageBuffer<##MESSAGE_TYPE> _##MESSAGE_TYPE; \
public: \
	void InsertMessage(##MESSAGE_TYPE message) \
	{ \
		_##MESSAGE_TYPE.InsertOutgoingMessage(message, messageStorage); \
	}

#define REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(MESSAGE_TYPE)\
	virtual void InsertMessage(##MESSAGE_TYPE message) = 0;

#define REGISTER_ALL_CANCEL()\
	REGISTER_OUTGOING_MESSAGE_CANCEL(Message)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(PlayerInputMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(TextMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(RelativeTransformMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(PlaySoundMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(PlayMovingSoundMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(StopSoundMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(ToggleGraphicsModuleMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(ApplyForceMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(MoveCameraRelativeToGameObjectMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(CollisionMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(PreparePaintSurfaceMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(PaintTrailForGameObjectMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(UpdatePositionMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(TextMeshMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(AddScoreHolderMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(ApplyImpulseMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(AbsoluteTransformMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(MoveGameObjectMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(ScaleGameObjectMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(RotateGameObjectMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(ToggleGameObjectMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(PlayAnimationMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(DebugLineMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(DebugSphereMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(UIQuadBatchMessage)\
	REGISTER_OUTGOING_MESSAGE_CANCEL(DummyWorkMessage)

#define REGISTER_ALL_CLEAR()\
	REGISTER_MESSAGE_CLEARER(Message)\
	REGISTER_MESSAGE_CLEARER(PlayerInputMessage)\
	REGISTER_MESSAGE_CLEARER(TextMessage)\
	REGISTER_MESSAGE_CLEARER(RelativeTransformMessage)\
	REGISTER_MESSAGE_CLEARER(PlaySoundMessage)\
	REGISTER_MESSAGE_CLEARER(PlayMovingSoundMessage)\
	REGISTER_MESSAGE_CLEARER(StopSoundMessage)\
	REGISTER_MESSAGE_CLEARER(ToggleGraphicsModuleMessage)\
	REGISTER_MESSAGE_CLEARER(ApplyForceMessage)\
	REGISTER_MESSAGE_CLEARER(MoveCameraRelativeToGameObjectMessage)\
	REGISTER_MESSAGE_CLEARER(CollisionMessage)\
	REGISTER_MESSAGE_CLEARER(PreparePaintSurfaceMessage)\
	REGISTER_MESSAGE_CLEARER(PaintTrailForGameObjectMessage)\
	REGISTER_MESSAGE_CLEARER(UpdatePositionMessage)\
	REGISTER_MESSAGE_CLEARER(TextMeshMessage)\
	REGISTER_MESSAGE_CLEARER(AddScoreHolderMessage)\
	REGISTER_MESSAGE_CLEARER(ApplyImpulseMessage)\
	REGISTER_MESSAGE_CLEARER(AbsoluteTransformMessage)\
	REGISTER_MESSAGE_CLEARER(MoveGameObjectMessage)\
	REGISTER_MESSAGE_CLEARER(ScaleGameObjectMessage)\
	REGISTER_MESSAGE_CLEARER(RotateGameObjectMessage)\
	REGISTER_MESSAGE_CLEARER(ToggleGameObjectMessage)\
	REGISTER_MESSAGE_CLEARER(PlayAnimationMessage)\
	REGISTER_MESSAGE_CLEARER(DebugLineMessage)\
	REGISTER_MESSAGE_CLEARER(DebugSphereMessage)\
	REGISTER_MESSAGE_CLEARER(UIQuadBatchMessage)\
	REGISTER_MESSAGE_CLEARER(DummyWorkMessage)

#define REGISTER_ALL_MESSAGES()\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(Message)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(PlayerInputMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(TextMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(RelativeTransformMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(PlaySoundMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(PlayMovingSoundMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(StopSoundMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(ToggleGraphicsModuleMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(ApplyForceMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(MoveCameraRelativeToGameObjectMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(CollisionMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(PreparePaintSurfaceMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(PaintTrailForGameObjectMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(UpdatePositionMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(TextMeshMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(AddScoreHolderMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(ApplyImpulseMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(AbsoluteTransformMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(MoveGameObjectMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(ScaleGameObjectMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(RotateGameObjectMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(ToggleGameObjectMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(PlayAnimationMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(DebugLineMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(DebugSphereMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(UIQuadBatchMessage)\
	REGISTER_LOCK_FREE_THREAD_SAFE_MESSAGE(DummyWorkMessage)

#define REGISTER_PURE_VIRTUAL_SERVICE()\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(Message)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(PlayerInputMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(TextMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(RelativeTransformMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(PlaySoundMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(PlayMovingSoundMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(StopSoundMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(ToggleGraphicsModuleMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(ApplyForceMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(MoveCameraRelativeToGameObjectMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(CollisionMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(PreparePaintSurfaceMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(PaintTrailForGameObjectMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(UpdatePositionMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(TextMeshMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(AddScoreHolderMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(ApplyImpulseMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(AbsoluteTransformMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(MoveGameObjectMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(ScaleGameObjectMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(RotateGameObjectMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(ToggleGameObjectMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(PlayAnimationMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(DebugLineMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(DebugSphereMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(UIQuadBatchMessage)\
	REGISTER_PURE_VIRTUAL_MESSAGE_SERVICE(DummyWorkMessage)